phpcs.xml, plugin/hook.php, plugin/install/install.php, plugin/setup.php
=> Added CodeSniffer config file

plugin/inc/profile.class.php
- Imported PluginIserviceProfile class from iService2 and ran code beautifier
=> EXL-301 - Imported PluginIserviceProfile class from iService2

plugin/inc/cartridge_ticket.class.php, plugin/inc/db.class.php, plugin/inc/partner.class.php, plugin/inc/printer.class.php, plugin/inc/ticket.class.php, plugin/inc/utils/redefinemenus.class.php, plugin/setup.php
- fixed empty hMarfa lastrun
- added populateByItemsId to fix iService object loading
- refactored getFromDBByQuery to PluginIserviceDB::populateByQuery
- ensured plugin related cache directory exists
=> Small fixes

plugin/js/iservice.js
Change will be visible after merge of https://github.com/pont-ro/glpi-iservice/pull/38
=> EXL-300 Renamed 'data_exp_fact' to 'invoice_expiry_date_field' in js

plugin/inc/hmarfa_invoicer.class.php, plugin/inc/utils/toolbox.class.php
- Added missing functions to Toolbox
- Added missing '-s
=> EXL-300 Small fixes

plugin/inc/specialviews/evaluation.class.php, plugin/inc/specialviews/facturiclient.class.php, plugin/inc/specialviews/tickets.class.php, plugin/inc/views/view.class.php
- Modified view.class.php to show counter only if show_limit === true
- Added show limit 'ajax' to views where setting was overwritten by special conditions
=> EXL-300 Modified view.class.php to show counter feature

plugin/ajax/import.php, plugin/config/import/Infocom.php, plugin/config/import/pluginiservicemovement.php, plugin/inc/consumable_ticket.class.php
- Added more details to import logging
- Fixed PluginIserviceMovement missing foreign key handling
- Added importInProgress session variable
=> EXL-274 Fixed Consumable Tickets and Infocoms import

plugin/ajax/generateSsx.php, plugin/ajax/managePrinter.php
- Ran code beautifier on managePrinter.php
=> EXL-318 Imported generate_ssx.php and ran code beautifier

plugin/ajax/import.php, plugin/inc/utils/toolbox.class.php, plugin/js/import.js, plugin/setup.php
- Improved import error logging
- Rremoved standard glpi logging on import
- Fixed UnpaidInvoices view link on invoicing page
=> EXL-318 Improved import error logging, removed glpi logging on import

plugin/config/config.php, plugin/config/import/cartridgeitem.php
- Removed clearCondition from cartridgeitem import config
=> EXL-318 Changed hmarfa.export.default_path config

plugin/css/iservice.css, plugin/inc/consumable_model.class.php, plugin/inc/hmarfa.class.php, plugin/inc/hmarfa_invoicer.class.php, plugin/inc/monthlyplan.class.php, plugin/inc/specialviews/contracts.class.php, plugin/inc/specialviews/emaintenance.class.php, plugin/inc/specialviews/intorders.class.php, plugin/inc/task_dataintegritytest.class.php, plugin/inc/views/stock.class.php, plugin/inc/views/stocklots.class.php, plugin/inc/views/view.class.php
- changed "clickable" to already existing "pointer" class
- design fixes for the views
- inhibited execution of data integrity tests if they are disabled from config
=> EXL-318 Code fixes

CustomCodeSnifferSniffs/Iservice/Sniffs/ImportedFiles/ChangeClassNamesSniff.php, CustomCodeSnifferSniffs/Iservice/readme.md, CustomCodeSnifferSniffs/Iservice/ruleset.xml, phpcs.xml, plugin/front/scanImportedFile.php
- Create custom CodeSniffer sniff to scan and replace old class names
=> EXL-318 - Created tool for scanning imported files

plugin/front/ticket.form.php, plugin/inc/ticket.class.php, plugin/inc/utils/toolbox.class.php
- Added Partner and Printer autofill based on get parameters
- Bug fixes
=> EXL-339 - Added Partner and Printer autofill based on get parameters

plugin/ajax/import.php
Fixed import bug caused by automatically calculated database columns
=> EXL-339 - Fixed import bug caused by automatically calculated DB columns

plugin/css/iservice.css, plugin/inc/cartridge_ticket.class.php, plugin/inc/cartridgeitem.class.php, plugin/inc/consumable_ticket.class.php, plugin/inc/item.class.php, plugin/inc/specialviews/cartridges.class.php, plugin/inc/specialviews/operations.class.php, plugin/inc/specialviews/printers.class.php, plugin/inc/specialviews/tickets.class.php, plugin/inc/ticket.class.php, plugin/inc/views/views.class.php, plugin/templates/components/fields_macros.html.twig, plugin/templates/pages/support/components/changeables_table.html.twig, plugin/templates/pages/support/components/consumables_table.html.twig, plugin/templates/pages/support/components/supplier_printer_location_unpaidi.html.twig, plugin/templates/pages/support/ticket.html.twig
- Added auto submit on dropdown select for 'Consumables' and 'Cartdidges' dropdowns
- Fixed page title to views
- Fixed hMarfa export csv
- Minor design fixes
=> EXL-339 - Fixed 'Cartridge' and 'Delivered' checkbox on ticket form

plugin/ajax/getPrinterCartridgesPopup.php, plugin/front/scanImportedFile.php, plugin/front/ticket.form.php, plugin/front/ticket.report.php, plugin/inc/cartridgeitem.class.php, plugin/inc/consumable_ticket.class.php, plugin/inc/emaintenance.class.php, plugin/inc/item.class.php, plugin/inc/movement.class.php, plugin/inc/specialviews/globalreadcounter.class.php, plugin/inc/specialviews/printers.class.php, plugin/inc/ticket.class.php
- Restored ['items_id']['Printer'][0] usage
=> EXL-352 - Implemented global counter reading

plugin/ajax/import.php, plugin/config/import/ticket.php
- Added junk data cleaning after import
- Disabled notifications on ticket import
=> EXL-274 - Added junk data cleaning after import

plugin/inc/installsteps/crontasksinstallstep.class.php, plugin/inc/printer.class.php, plugin/inc/printerdailyaveragecalculator.class.php, plugin/inc/ticket.class.php, plugin/inc/views/operations.class.php, plugin/inc/views/printercounters.class.php, plugin/inc/views/printers.class.php, plugin/inc/views/tickets.class.php, plugin/install/sql/create_views.sql, plugin/setup.php
- Implemented PrinterCounters
- Created PrinterDailyAverageCalculator cron job
=> EXL-341 - Implemented PrinterCounters

plugin/config/additional_tables_settings.php, plugin/front/views.php, plugin/inc/intorder.class.php, plugin/inc/views/intorders.class.php, plugin/inc/views/view.class.php, plugin/templates/pages/support/components/buttons.html.twig
- Fixed csrf token error
- Added caching to internal orders view
=> EXL-366 - Fixed 'Add' button positions

plugin/config/config.php, plugin/config/database_tables.php, plugin/css/iservice.css, plugin/inc/views/intorders.class.php, plugin/inc/views/view.class.php, plugin/setup.php
- Removed caching from intorders
- Fixed plugin version number
- Fixed view columns sorting icon
=> EXL-366 - Added missing index on glpi_cartridgeitems

plugin/front/intorder.form.php, plugin/front/views.php, plugin/inc/extorder.class.php, plugin/inc/intorder.class.php, plugin/inc/movement.class.php, plugin/inc/printer.class.php, plugin/inc/profile.class.php, plugin/inc/ticket.class.php, plugin/inc/utils/toolbox.class.php, plugin/inc/views/emaintenance.class.php, plugin/inc/views/intorders.class.php, plugin/inc/views/printers.class.php, plugin/inc/views/tickets.class.php, plugin/templates/pages/support/components/buttons.html.twig, plugin/templates/pages/support/components/supplier_printer_location_unpaidi.html.twig
- Fixed missing "Save" button on intorder edit
- Modified filter condition on intorders view for "Solicitant" column
=> EXL-366 - Fixed missing "Save" button on intorder edit

plugin/front/ticket.form.php, plugin/inc/cartridgeitem.class.php, plugin/inc/item.class.php, plugin/inc/rights.config.php, plugin/inc/ticket.class.php, plugin/inc/tickettemplate.class.php, plugin/inc/views/printers.class.php, plugin/templates/components/fields_macros.html.twig, plugin/templates/pages/support/components/supplier_printer_location_unpaidi.html.twig, plugin/templates/pages/support/components/title_content.html.twig, plugin/templates/pages/support/ticket.html.twig
- Fixed read counter ticket creation for client and superclient
- Added functionality to remove or render fields as hidden based on profile
- Added ticket right 127 to client and superclient profiles
- Fixed 'effective_date_field' update bugs
=> EXL-379 tickets from clients

plugin/inc/views/evaluation.class.php, plugin/inc/views/inboundlots.class.php, plugin/inc/views/outboundlots.class.php, plugin/inc/views/routemanifest.class.php, plugin/inc/views/tickets.class.php, plugin/inc/views/unpaidinvoices.class.php, plugin/inc/views/view.class.php, plugin/templates/pages/support/inquiry.html.twig
- Modified Inquiry form to use our own buttons component, so that Add button in aligned to the center
- Added 'class' parameter to view filter_data
- Fixed additional filters spacing in Tickets view
- Fixed additional filters spacing in UnpaidInvoices view
- Fixed additional filters spacing in OutboundLots view
- Fixed additional filters spacing in InboundLots view
- Fixed additional filters spacing in RouteManifest view
- Fixed additional filters spacing in Evaluation view
=> EXL-384 Design fixes

plugin/inc/cartridge_ticket.class.php, plugin/inc/item.class.php, plugin/inc/ticket.class.php, plugin/inc/views/cartridges.class.php, plugin/inc/views/evaluation.class.php, plugin/inc/views/inboundlots.class.php, plugin/inc/views/outboundlots.class.php, plugin/inc/views/routemanifest.class.php, plugin/inc/views/tickets.class.php, plugin/inc/views/unpaidinvoices.class.php, plugin/inc/views/view.class.php, plugin/templates/components/fields_macros.html.twig, plugin/templates/pages/support/components/changeables_table.html.twig, plugin/templates/pages/support/inquiry.html.twig, plugin/templates/pages/support/ticket.html.twig
- Added functionality to check if installation date field is higher the effective date field
- Added alert in date from CSV is lower than minimum required effective date
- Added "Yesterday and Today" buttons to installation date field
- Added functionality to make installation date field equal with effective date, unless it was manually changed
- Disabled every filed on ticket form when ticket is closed
- Bug fixes
=> EXL-390 - Made category field required

plugin/inc/ticket.class.php, plugin/templates/pages/support/components/changeables_table.html.twig
- Fixed error message display in case there is a newer ticket with installed cartridge
=> EXL-390 - Fixed error message display

plugin/inc/reminder.class.php
=> EXL-392 - Fixed PluginIserviceReminder:showForm method, Description filed

plugin/inc/cartridgeverifier.class.php, plugin/inc/views/view.class.php
- Added logging to PluginIserviceCartridgeVerifier when no cartridge is returned
=> EXL-358 - Cachetable naming bugfix

plugin/inc/reminder.class.php
Changed PluginIserviceReminder::$rightname from "reminder_public" to "plugin_iservice_view_reminders".
=> EXL-392 - Changed PluginIserviceReminder::$rightname

plugin/inc/monthlyplan.class.php
Added yellow background color on monthly plan for companies where there was movements in the last 40 days
=> EXL-462 - Monthly plan coloring

plugin/inc/views/view.class.php, plugin/js/iservice.js
=> EXL-471 - Fixed setGlpiDateField method

plugin/inc/cartridgeitem.class.php, plugin/inc/dataintegrity_tests/cartridgeitemtypedropdowns_id_empty.php
- Fixed empty type on cartridge creation
- Created self test to monitor cartridges with plugin_fields_cartridgeitemtypedropdowns_id
=> EXL-480 - Fixed empty type on cartridge creation

plugin/ajax/setContractSupplier.php, plugin/inc/dataintegrity_tests/contracts_without_supplier.php
- Created self test to find contracts without suppliers
- Created Query to fix the issue
=> EXL-479 - Created self test to find contracts without suppliers

plugin/inc/ticket.class.php, plugin/templates/pages/support/components/cartridges_consumables_table.html.twig, plugin/templates/pages/support/ticket.html.twig
=> EXL-470 - Added Cartridges and Consumables data to ticket

plugin/css/iservice.css, plugin/inc/views/tickets.class.php, plugin/inc/views/view.class.php, plugin/templates/pages/support/components/cartridges_consumables_table.html.twig, plugin/templates/pages/support/components/consumables_section.html.twig, plugin/templates/pages/support/components/effective_date.html.twig, plugin/templates/pages/support/components/export_type.html.twig, plugin/templates/pages/support/components/printer_counter.html.twig, plugin/templates/pages/support/components/status_and_checkboxes.html.twig, plugin/templates/pages/support/components/supplier_printer_location_unpaidi.html.twig, plugin/templates/pages/support/ticket.html.twig
- Added different background color for different section on Ticket form
- Added dark orange and bold style for partner name display when having 3 unpaid invoices
- Removed additional location information in form printer name in ticket list
=> EXL-488 - Small design changes

plugin/front/ticket.form.php, plugin/inc/ticket.class.php, plugin/locales/ro_RO.po
Fixed bug the caused empty tickets when cartridge install date was greater than effective date
=> EXL-485 - Fixed bug the caused empty tickets when cartridge install date was greater than effective date

plugin/front/qr.form.php, plugin/inc/qr.class.php, plugin/js/iservice.js, plugin/setup.php, plugin/templates/parts/page_header.html.twig
- Fixed QR file upload
- Fixed url in QR form header
=> EXL-514 - Fixed QR file upload
